//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Productid { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProductShortDesc { get; set; }
        public string ProductFullDesc { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductMainGroupId { get; set; }
        public Nullable<int> ProductSubGroupId { get; set; }
        public Nullable<int> ProductSubChildGroupId { get; set; }
        public string AssemblyType { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> LocalTaxRate { get; set; }
        public Nullable<decimal> CentralTaxRate { get; set; }
        public Nullable<decimal> OtherTaxRate { get; set; }
        public Nullable<bool> IsSerializedProduct { get; set; }
        public string BrandName { get; set; }
        public Nullable<decimal> ReOrderQty { get; set; }
        public Nullable<decimal> MinOrderQty { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CGST_Perc { get; set; }
        public Nullable<decimal> SGST_Perc { get; set; }
        public Nullable<decimal> IGST_Perc { get; set; }
        public string HSN_Code { get; set; }
        public Nullable<bool> GST_Exempt { get; set; }
        public string BarCode { get; set; }
        public byte[] BarCodeImage { get; set; }
    }
}
