//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public long BrandID { get; set; }
        public string BrandName { get; set; }
        public long ProductMainGroupId { get; set; }
        public long ProductSubGroupId { get; set; }
        public long ProductSubChildGroupId { get; set; }
    }
}
