//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeUpdate
    {
        public long UpdateId { get; set; }
        public string UpdateTitle { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateArea { get; set; }
        public string UpdateDec { get; set; }
        public string UpdateUrl { get; set; }
        public string ImageUrl { get; set; }
        public string ImageTitile { get; set; }
        public string ImageNavigateUrl { get; set; }
        public string ImageAlt { get; set; }
        public Nullable<bool> UpdateStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
