//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    
    public partial class proc_GetHomeSubChildMenu_Result
    {
        public Nullable<int> SubMenuId { get; set; }
        public string SubChildMenuName { get; set; }
        public string SubChildMenuLink { get; set; }
        public Nullable<bool> SubChildMenuStatus { get; set; }
    }
}
