//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayInfo
    {
        public long PayInfoId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> OTRate { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> ConveyanceAllow { get; set; }
        public Nullable<decimal> SpecialAllow { get; set; }
        public Nullable<decimal> OtherAllow { get; set; }
        public Nullable<decimal> OtherDeduction { get; set; }
    }
}
