//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubChildGroup
    {
        public long ProductSubChildGroupId { get; set; }
        public string ProductSubChildGroupName { get; set; }
        public string ProductSubChildGroupCode { get; set; }
        public Nullable<long> ProductMainGroupId { get; set; }
        public Nullable<long> ProductSubGroupId { get; set; }
        public string ProductSubChildGroupDesc { get; set; }
        public string ProductSubChildGroupImageUrl { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
