//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceTaxDetail
    {
        public long InvoiceTaxDetailId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<long> TaxId { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<bool> CFormApplicable { get; set; }
        public string CFormStatus { get; set; }
        public string CFormNo { get; set; }
        public Nullable<System.DateTime> CFormDate { get; set; }
        public string CFormRemarks { get; set; }
    }
}
