//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public int SubMenuId { get; set; }
        public int MenuId { get; set; }
        public string PageName { get; set; }
        public string SubMenuName { get; set; }
        public string SubMenuLink { get; set; }
        public Nullable<bool> SubMenuStatus { get; set; }
        public Nullable<int> SequenceNo { get; set; }
    }
}
