//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public long UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string AlternateContactno { get; set; }
        public string WhatsaapPhone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> StateId { get; set; }
        public string City { get; set; }
        public string SubCity { get; set; }
        public string Landmark { get; set; }
        public string BuildingNo { get; set; }
        public string PINCode { get; set; }
        public string GSTNo { get; set; }
        public string PANNo { get; set; }
        public string UdyogAadhaarNo { get; set; }
        public string KYCCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public string UserCode { get; set; }
    }
}
